/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.gym.ui;

import com.gym.buiseness.PrintBMIReport;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class BmiChart extends JFrame{
    float value1,value2,value3,value4,value5,value6,value7,value8,value9,value10,pound,kg;
String gen;
    public BmiChart() {
        super("BMI Chart...!");
        initComponents();
        jTextField4.setEnabled(false);
        jTextField5.setEnabled(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        getContentPane().setBackground(Color.white);
        setResizable(false);
        
    }
    public void getBMI()
    {
        float height = 0,weight=0;
        height=Float.parseFloat(jTextField3.getText());
        weight=Float.parseFloat(jTextField2.getText());
        float mtr=height/3.2808f;
        jTextField4.setText(String.valueOf(mtr));
        float sqr=(float)Math.pow(mtr, 2);
        float bmi=weight/sqr;
        jTextField5.setText(String.valueOf(bmi));
        if(bmi>=18.5 && bmi<=24.9)
        {
            JOptionPane.showMessageDialog(rootPane, "you are under Normal weight","BMI Chart Message",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(bmi>24.9)
        {
            if(bmi>29.9)
            {
            JOptionPane.showMessageDialog(rootPane, "Obese","BMI Chart Message",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Overweight","BMI Chart Message",JOptionPane.ERROR_MESSAGE);
            }
        }
        else if(bmi < 18.5)
        {
            JOptionPane.showMessageDialog(rootPane, "Underweight", "BMI Chart Message",JOptionPane.ERROR_MESSAGE);
        }
        
             
             
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter Name:");

        jTextField1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setText("Enter Weight(Kg):");

        jTextField2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setText("Enter Height(ft):");

        jTextField3.setBackground(new java.awt.Color(204, 204, 255));
        jTextField3.setText("0");

        jTextField4.setBackground(new java.awt.Color(204, 204, 255));
        jTextField4.setText("0");

        jButton1.setMnemonic('C');
        jButton1.setText("Calculate");
        jButton1.setToolTipText("Calculate the BMI report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("BMI :");

        jTextField5.setBackground(new java.awt.Color(204, 204, 255));

        jLabel5.setText("Enter waist(inchs):");

        jTextField6.setBackground(new java.awt.Color(204, 204, 255));

        jLabel6.setText("Fat(%):");

        jTextField7.setBackground(new java.awt.Color(204, 204, 255));

        jButton2.setText("Calculate Fat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Wrist(inchs):");

        jTextField8.setBackground(new java.awt.Color(204, 204, 255));
        jTextField8.setText("0");

        jTextField9.setBackground(new java.awt.Color(204, 204, 255));
        jTextField9.setText("0");

        jLabel8.setText("Forearm(inchs):");

        jTextField10.setBackground(new java.awt.Color(204, 204, 255));
        jTextField10.setText("0");

        jLabel9.setText("Hips(inchs):");

        jButton3.setText("Print Report");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       getBMI();
    }                                        
    public void calculateFatForMan()
    {
        kg=Float.parseFloat(jTextField2.getText());
        pound=kg*2.2046f;
        float waist=Float.parseFloat(jTextField6.getText());
        float val1=(pound*1.082f)+94.42f;
        float val2=(waist*4.15f);
        float lbm=val1-val2;
        float val3=pound-lbm;
        float bmass=val3/pound*100;
        jTextField7.setText(String.valueOf(bmass));
    }
    public void calculateFatForWoman()
    {
        kg=Float.parseFloat(jTextField2.getText());
        float waist=Float.parseFloat(jTextField6.getText());
        float hips=Float.parseFloat(jTextField10.getText());
        float forearm=Float.parseFloat(jTextField9.getText());
        pound=kg*2.2046f;
        value1=pound*0.732f;
        value2=value1+8.987f;
        value3=waist/3.14f;
        value4=waist*0.157f;
        value5=hips*0.249f;
        value6=forearm*0.434f;
        value7=value2+value3;
        value8=value7-value4;
        value9=value8-value5;
        float lbm=value6+value9;
        value10=pound-lbm;
        float fat=value10/pound*100;
        jTextField7.setText(String.valueOf(fat));
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       if(gen.equalsIgnoreCase("male"))
           calculateFatForMan();
       else
           calculateFatForWoman();
    }                                        
    
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
       jTextField8.setEnabled(false);
       jTextField9.setEnabled(false);
       jTextField10.setEnabled(false);
       gen="male";
    }                                             

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
       jTextField8.setEnabled(true);
       jTextField9.setEnabled(true);
       jTextField10.setEnabled(true);
       gen="female";
    }                                             

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try{
            String name,gender,height,weight,bmi,fat,category = null,waist,wrist,forearm,hips;
            gender=gen;
            name=jTextField1.getText();
            height=jTextField3.getText();
            weight=jTextField2.getText();
            bmi=jTextField5.getText();
            waist=jTextField6.getText();
            wrist=jTextField8.getText();
            hips=jTextField10.getText();
            forearm=jTextField9.getText();
            fat=jTextField7.getText();
            float f=Float.parseFloat(fat);
            if(gender.equals("male"))
            {
                if(f>=2 && f<=4)
                {
                    category="Essential Fat";
                }
                else if(f>=6 && f<=13)
                {
                    category="Athletic";
                }
                else if(f>=14 && f<=17)
                {
                    category="Fitness";
                }
                else if(f>=18 && f<=25)
                {
                    category="average";
                }
                else if(f>=26)
                {
                    category="Obese";
                }
            }
            else
            {
                if(f>=10 && f<=12)
                {
                    category="Essential Fat";
                }
                else if(f>=14 && f<=20)
                {
                    category="Athletic";
                }
                else if(f>=21 && f<=24)
                {
                    category="Fitness";
                }
                else if(f>=25 && f<=31)
                {
                    category="average";
                }
                else if(f>=32)
                {
                    category="Obese";
                }
            }
            PrintBMIReport pbm=new PrintBMIReport();
            pbm.jLabel12.setText(name);
            pbm.jLabel13.setText(gender);
            pbm.jLabel14.setText(weight);
            pbm.jLabel15.setText(height);
            pbm.jLabel16.setText(bmi);
            pbm.jLabel17.setText(waist);
            pbm.jLabel18.setText(wrist);
            pbm.jLabel19.setText(forearm);
            pbm.jLabel20.setText(hips);
            pbm.jLabel21.setText(fat);
            pbm.jLabel22.setText(category);
            pbm.setVisible(rootPaneCheckingEnabled);
                    
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BmiChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BmiChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BmiChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BmiChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BmiChart().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    public javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration                
}
