/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gym.general.addmember;

import com.gym.buiseness.Biometric_Attendance;
import java.awt.EventQueue;
import java.io.IOException;
import javax.swing.JPanel;
import javax.swing.UIManager;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DELL
 */
class window implements Runnable{

    @Override
    public void run() {
        try {
            //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            System.out.println("New Thread Started");
            Process pp=Runtime.getRuntime().exec("cmd /c "+"\"C:\\Program Files (x86)\\Attendance Management System\\AttendanceTracker11.8\\AttendanceTracker11.8.exe\"");
        } catch (IOException ex) {
            Logger.getLogger(window.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
}

public class Add extends javax.swing.JFrame {

    private JPanel Contentpane;
    
    
     public static void main(String[] args) throws IOException {
		
         
         
		try {
               
                    
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
            String filepath="C:\\Program Files (x86)\\Attendance Management System\\AttendanceTracker11.8\\AttendanceTracker11.8.exe";
            //Process pp=Runtime.getRuntime().exec("C:\\Program Files (x86)\\Attendance Management System\\AttendanceTracker11.8\\AttendanceTracker11.8");
            
          
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biometric_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biometric_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biometric_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biometric_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					Add frame = new Add();
					frame.setVisible(true);
                                        
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
                
                window wobject=new window();
                Thread t1=new Thread(wobject);
                t1.start();
	
     }
   
    
    public Add() throws IOException {
        initComponents();
        try {
             
        } catch (Exception e) {
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
